version: 3

# silent: true

vars:
  SERVICE_FUNCTION_NAME: darex-service

tasks:
  _zip:
    dir: dist
    cmds:
      - zip index.zip index.js > /dev/null
  build:
    cmds:
      - mkdir -p dist/
      - yarn build
      - task _zip
  deploy:
    dir: dist
    cmds:
      - task build
      - "aws lambda update-function-code --function-name {{ .SERVICE_FUNCTION_NAME }} --zip-file fileb://index.zip > ../log/service.json"
