version: 3

# silent: true

vars:
  SERVICE_FUNCTION_NAME: darex

tasks:
  _zip:
    dir: dist/service/
    cmds:
      - zip index.zip index.js > /dev/null
  build:
    cmds:
      - mkdir -p dist/service/
      - yarn build
      - task _zip
  deploy:
    dir: dist/service/
    cmds:
      - task build
      - mkdir -p ../../log/
      - "aws lambda update-function-code --function-name {{ .SERVICE_FUNCTION_NAME }} --zip-file fileb://index.zip > ../../log/service.json"
